In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
%matplotlib inline

In [6]:
df = pd.read_csv('../data_sets/single_family_home_values.csv') #zillow

In [7]:
df.head(5)

id              address    city state  zipcode   latitude  \
0   39525749      8171 E 84th Ave  Denver    CO    80022  39.849160   
1  184578398    10556 Wheeling St  Denver    CO    80022  39.888020   
2  184430015  3190 Wadsworth Blvd  Denver    CO    80033  39.761710   
3  155129946  3040 Wadsworth Blvd  Denver    CO    80033  39.760780   
4     245107      5615 S Eaton St  Denver    CO    80123  39.616181   

    longitude  bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt  \
0 -104.893468         3        2.0      6           1378     9968     2003.0   
1 -104.830930         2        2.0      6           1653     6970     2004.0   
2 -105.081070         3        1.0      0           1882    23875     1917.0   
3 -105.081060         4        3.0      0           2400    11500     1956.0   
4 -105.058812         3        4.0      8           2305     5600     1998.0   

  lastSaleDate  lastSaleAmount priorSaleDate  priorSaleAmount  estimated_value  
0   2009-12-17           75000    2004-05-13         165700.0           239753  
1   2004-09-23          216935           NaN              NaN           343963  
2   2008-04-03          330000           NaN              NaN           488840  
3   2008-12-02          185000    2008-06-27              0.0           494073  
4   2012-07-18          308000    2011-12-29              0.0           513676

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               15000 non-null  int64  
 1   address          15000 non-null  object 
 2   city             15000 non-null  object 
 3   state            15000 non-null  object 
 4   zipcode          15000 non-null  int64  
 5   latitude         14985 non-null  float64
 6   longitude        14985 non-null  float64
 7   bedrooms         15000 non-null  int64  
 8   bathrooms        15000 non-null  float64
 9   rooms            15000 non-null  int64  
 10  squareFootage    15000 non-null  int64  
 11  lotSize          15000 non-null  int64  
 12  yearBuilt        14999 non-null  float64
 13  lastSaleDate     15000 non-null  object 
 14  lastSaleAmount   15000 non-null  int64  
 15  priorSaleDate    11173 non-null  object 
 16  priorSaleAmount  11287 non-null  float64
 17  estimated_va

In [9]:
df.describe()

id       zipcode      latitude     longitude      bedrooms  \
count  1.500000e+04  15000.000000  14985.000000  14985.000000  15000.000000   
mean   5.176229e+07  80204.919467     39.740538   -104.964076      2.708400   
std    6.190876e+07      9.715263      0.023555      0.039788      0.897231   
min    1.433670e+05  80022.000000     39.614531   -105.108440      0.000000   
25%    1.004802e+07  80205.000000     39.727634   -104.978737      2.000000   
50%    2.563241e+07  80206.000000     39.748048   -104.957689      3.000000   
75%    5.114222e+07  80207.000000     39.758214   -104.937522      3.000000   
max    3.209481e+08  80209.000000     39.888020   -104.830930     15.000000   

          bathrooms         rooms  squareFootage       lotSize     yearBuilt  \
count  15000.000000  15000.000000   15000.000000   15000.00000  14999.000000   
mean       2.195067      6.164133    1514.504400    5820.76620   1929.517168   
std        1.166279      1.958601     830.635999    3013.27947     29.937051   
min        0.000000      0.000000     350.000000     278.00000   1874.000000   
25%        1.000000      5.000000     986.000000    4620.00000   1907.000000   
50%        2.000000      6.000000    1267.500000    5950.00000   1925.000000   
75%        3.000000      7.000000    1766.250000    6270.00000   1949.000000   
max       12.000000     39.000000   10907.000000  122839.00000   2016.000000   

       lastSaleAmount  priorSaleAmount  estimated_value  
count    1.500000e+04     1.128700e+04     1.500000e+04  
mean     4.053563e+05     2.594350e+05     6.371625e+05  
std      7.756998e+05     3.379387e+05     5.044185e+05  
min      2.590000e+02     0.000000e+00     1.477670e+05  
25%      1.940000e+05     1.100000e+05     3.984348e+05  
50%      3.200000e+05     2.100000e+05     5.183575e+05  
75%      4.632000e+05     3.302400e+05     6.879692e+05  
max      4.560000e+07     1.600000e+07     1.014531e+07

In [ ]:
# drop/delete column using below

In [11]:
df.drop('estimated_value', axis=1)
# or 
df2=df.drop('estimated_value', axis=1)
# or 
X = df.drop('estimated_value', axis=1)


In [46]:
X = X[['bedrooms','bathrooms','rooms','squareFootage','lotSize', 'yearBuilt','priorSaleAmount']]

In [13]:
X.head(2)

bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt  \
0         3        2.0      6           1378     9968     2003.0   
1         2        2.0      6           1653     6970     2004.0   

   priorSaleAmount  
0         165700.0  
1              NaN

In [47]:
X.fillna(0, inplace=True)

In [21]:
X.head(2)

bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt  \
0         3        2.0      6           1378     9968     2003.0   
1         2        2.0      6           1653     6970     2004.0   

   priorSaleAmount  
0         165700.0  
1              0.0

In [25]:
kmean = KMeans(n_clusters = 5, random_state=0).fit(X)

In [27]:
kmean

KMeans(n_clusters=5, random_state=0)

In [35]:
labels= kmeans.labels_

In [ ]:
# labels should equal len of array

In [28]:
len(kmeans.labels_), X.shape

(15000, (15000, 7))

In [29]:
kmeans.cluster_centers_

array([[3.31226296e+00, 3.83944374e+00, 8.42730721e+00, 2.69720607e+03,
        6.97174968e+03, 1.94200506e+03, 7.43586930e+05],
       [2.64078392e+00, 1.93525180e+00, 5.86293724e+00, 1.39300918e+03,
        5.94409712e+03, 1.93060060e+03, 3.93563157e+04],
       [3.00000000e+00, 4.50000000e+00, 9.00000000e+00, 3.74800000e+03,
        8.59750000e+03, 1.99800000e+03, 1.37500550e+07],
       [3.73118280e+00, 5.64516129e+00, 1.04408602e+01, 4.51996774e+03,
        1.30122688e+04, 1.96766667e+03, 2.37729552e+06],
       [2.70373430e+00, 2.27247191e+00, 6.20290813e+00, 1.47484848e+03,
        5.39461203e+03, 1.92551404e+03, 2.93157062e+05]])

In [36]:
X['cluster'] = labels

In [37]:
X.head(2)

bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt  \
0         3        2.0      6           1378     9968     2003.0   
1         2        2.0      6           1653     6970     2004.0   

   priorSaleAmount  cluster  
0         165700.0        1  
1              0.0        1

In [38]:
X.groupby('cluster').mean() # can also do .min, .mean. max ,etc.

bedrooms  bathrooms      rooms  squareFootage       lotSize  \
cluster                                                                
0        3.312263   3.839444   8.427307    2697.206068   6971.749684   
1        2.641226   1.935344   5.863614    1393.248821   5944.416232   
2        3.000000   4.500000   9.000000    3748.000000   8597.500000   
3        3.731183   5.645161  10.440860    4519.967742  13012.268817   
4        2.703104   2.272127   6.201783    1474.475561   5394.550363   

           yearBuilt  priorSaleAmount  
cluster                                
0        1942.005057     7.435869e+05  
1        1930.599901     3.929321e+04  
2        1998.000000     1.375006e+07  
3        1967.666667     2.377296e+06  
4        1925.518329     2.930734e+05

In [31]:
kmeans.cluster_centers_[0]

array([3.31226296e+00, 3.83944374e+00, 8.42730721e+00, 2.69720607e+03,
       6.97174968e+03, 1.94200506e+03, 7.43586930e+05])

In [32]:
X.head(3)

bedrooms  bathrooms  rooms  squareFootage  lotSize  yearBuilt  \
0         3        2.0      6           1378     9968     2003.0   
1         2        2.0      6           1653     6970     2004.0   
2         3        1.0      0           1882    23875     1917.0   

   priorSaleAmount  
0         165700.0  
1              0.0  
2              0.0

# for loop to generate number of clusters/groupings 

In [39]:
X= X.drop('cluster', axis=1)

In [43]:
from sklearn.metrics import silhouette_score

In [45]:
for i in range(3,10):
    kmeans= KMeans(n_clusters=i).fit(X)
    labels = kmeans.labels_
    print (silhouette_score(X, labels))

0.6145730276990463
0.6165719209971882
0.6336594067404021
0.643438596521382
0.6592385755144206
0.660940918441709
0.6574902072195434


In [41]:
for i in range(3,10):
    kmeans= KMeans(n_clusters=i).fit(X)
    print (kmeans.labels_)
    print (kmeans.cluster_centers_)

[0 0 0 ... 1 1 1]
[[2.62802971e+00 1.94096951e+00 5.82730649e+00 1.37072322e+03
  5.84289582e+03 1.93036484e+03 7.39829665e+04]
 [2.86277873e+00 2.67624357e+00 6.80960549e+00 1.76360142e+03
  5.61970026e+03 1.92636042e+03 4.09301798e+05]
 [3.69230769e+00 5.61538462e+00 1.03557692e+01 4.48931731e+03
  1.26605865e+04 1.96913462e+03 2.52178569e+06]]
[0 0 0 ... 1 2 2]
[[2.62955835e+00 1.93527147e+00 5.82536467e+00 1.37173369e+03
  5.86515367e+03 1.93050932e+03 6.81113908e+04]
 [3.68589744e+00 5.50000000e+00 1.03461538e+01 4.28346795e+03
  1.13758974e+04 1.97144231e+03 1.94650854e+06]
 [2.83420523e+00 2.60643863e+00 6.70462777e+00 1.71028048e+03
  5.55711489e+03 1.92581469e+03 3.87261955e+05]
 [3.00000000e+00 4.50000000e+00 9.00000000e+00 3.74800000e+03
  8.59750000e+03 1.99800000e+03 1.37500550e+07]]
[0 1 1 ... 4 0 4]
[[2.69675623e+00 2.26032110e+00 6.18299476e+00 1.46704817e+03
  5.39934371e+03 1.92557176e+03 2.89554681e+05]
 [2.64373588e+00 1.93760984e+00 5.86806427e+00 1.39591150e+03
  