In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
A = np.array([[1,2,3], [4,5,6]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
B = np.array([[7,8,9], [10,11,12]])

In [6]:
np.dot(A,B.T)

array([[ 50,  68],
       [122, 167]])

In [7]:
C= A ** 2

In [8]:
C

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
D = A-1

In [10]:
D

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
C2 = np.array([[1,2,3],[1,2,3], [3,4,5]])

In [15]:
C2

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [16]:
C2.diagonal()

array([1, 2, 5])

In [17]:
A = np.matrix(A)

In [18]:
type(A)

numpy.matrix

In [19]:
B = np.matrix(B)

In [21]:
C = np.matrix(C)

In [22]:
A.nonzero() # REturn indices of the elements that are non-zero

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [23]:
A - B

matrix([[-6, -6, -6],
        [-6, -6, -6]])

In [24]:
A + B

matrix([[ 8, 10, 12],
        [14, 16, 18]])

In [26]:
A.dot(B.T)

matrix([[ 50,  68],
        [122, 167]])

In [27]:
A.sum()

21

In [36]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [37]:
print (A.sum(), A.mean(), A.std(), A.var())

21 3.5 1.707825127659933 2.9166666666666665


In [38]:
A_df

0  1  2
0  1  2  3
1  4  5  6

In [39]:
type(A_df)

pandas.core.frame.DataFrame